version: ~> 1.0 # needed for imports

import: scala/scala-dev:travis/default.yml

language: scala

scala:
  - "2.11.12"
  - "2.12.10"
  - "2.13.1"

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork AND (env(ADOPTOPENJDK) = 8)

jobs:
  include:
    - stage: release
      script: sbt ci-release
